version: "3.8"

services:
  android-emulator:
    image: budtmo/docker-android-x86-11.0
    privileged: true
    ports:
      - "4723:4723"    # Appium
      - "6080:6080"    # VNC viewer (optional)
      - "5554:5554"
      - "5555:5555"
    environment:
      - DEVICE=Samsung Galaxy S6
      - APPIUM=true
    volumes:
      - ./wdio/app.apk:/root/tmp/app.apk

  wdio:
    build: ./wdio
    depends_on:
      - android-emulator
    working_dir: /usr/src/app
